### ISSUE TITLE
deploy-ad script potential issue

### ISSUE THREAD

**Issue by paulopsgility** [opsgility/lab-support-public#5]
There was an issue reported in the Building Resillient IaaS cloud workshop repo where they were not able to run a DNS powershell cmdlet. To fix it I updated the ad deployment script in here https://github.com/opsgility/cw-building-resilient-iaas-architecture/tree/master/script-extensions to explicitly install the DNS feature. Prior to that it was pulling the deploy-as.ps1 from this repo.

We need to 

A) Determine if this is a bigger problem that impacts other labs (list of impacted labs)
B) If so, verify that my fix is the right fix
C) Fix this in all of our custom script extensions that do ad installs. (it may be more than just this one.

**Comment by ciphertxt** [comment]
DNS is automatically installed as a part of Install-ADDSForest. There is an optional parameter on that cmdlet that deploys DNS (-InstallDns) that defaults to $True on a new forest install (https://docs.microsoft.com/en-us/powershell/module/addsdeployment/install-addsforest?view=win10-ps#optional-parameters) so the existing script as-is works. If the **DNS cmdlets** are required then the way you did it at https://github.com/opsgility/cw-building-resilient-iaas-architecture/blob/master/script-extensions/deploy-ad.ps1 is the way to go as that will lay down the GUI management tools in addition to the DNS Server Po$h module.

**Comment by paulopsgility** [comment]
@ciphertxt I am thinking we should just add this to our regular deploy-ad.ps1 script just in case some other lab depends on it. Any downside to that?

**Comment by ciphertxt** [comment]
Nope, I went ahead and updated the base script at https://github.com/opsgility/lab-support-public/blob/master/script-extensions/deploy-ad.ps1 to incorporate it.
